version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8005:8005"
    volumes:
      - shared-data:/app/data
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - shared-data:/app/data
    restart: always

volumes:
  shared-data:
